1. Импорт библиотеки NumPy с общепринятым сокращением.

In [1]:
import numpy as np

2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.


In [ ]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 6 4]


In [3]:
b = np.zeros((5, 6)) 
c = np.ones((3,4))
d = np.arange(1, 15, 2)

display(b, c, d)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([ 1,  3,  5,  7,  9, 11, 13])

3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.


In [4]:
print(c.shape)
print(c.dtype)

(3, 4)
float64


4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [5]:
print(d[3], d[-2])
print(d[2:5])

7 11
[5 7 9]


5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.


In [ ]:
print(d + d, d * d)
print(d.mean(), d.std())

[ 2  6 10 14 18 22 26] [  1   9  25  49  81 121 169]
7.0 4.0
